package com.simpati.bontoharu.simpatika;
import android.app.AlertDialog; import android.text.InputType; import android.view.LayoutInflater; import android.view.View; import android.view.ViewGroup; import android.widget.Button; import android.widget.EditText; import android.widget.TextView; import android.widget.Toast;
import androidx.annotation.NonNull; import androidx.recyclerview.widget.RecyclerView;
import com.google.firebase.firestore.FirebaseFirestore;
import java.util.ArrayList;
public class PagadeAdapter extends RecyclerView.Adapter<PagadeAdapter.VH> {
  private ArrayList<PagadeProduct> list; private FirebaseFirestore db;
  public PagadeAdapter(ArrayList<PagadeProduct> list, FirebaseFirestore db){ this.list=list; this.db=db; }
  @NonNull @Override public VH onCreateViewHolder(@NonNull ViewGroup parent,int viewType){ View v=LayoutInflater.from(parent.getContext()).inflate(R.layout.item_product,parent,false); return new VH(v); }
  @Override public void onBindViewHolder(@NonNull VH holder,int position){ PagadeProduct p=list.get(position); holder.tvName.setText(p.getNama()); holder.tvPrice.setText("Rp "+p.getHarga()); holder.tvStock.setText("Stok: "+p.getStok()); holder.btnEditStock.setOnClickListener(v->showEditStock(holder,p)); holder.btnDelete.setOnClickListener(v->{ db.collection("pagade_produk").document(p.getId()).delete().addOnSuccessListener(a->{ Toast.makeText(holder.itemView.getContext(),"Produk dihapus",Toast.LENGTH_SHORT).show(); list.remove(position); notifyItemRemoved(position); }).addOnFailureListener(e->Toast.makeText(holder.itemView.getContext(),"Gagal: "+e.getMessage(),Toast.LENGTH_LONG).show()); }); }
  private void showEditStock(VH holder, PagadeProduct p){ AlertDialog.Builder b=new AlertDialog.Builder(holder.itemView.getContext()); b.setTitle("Edit Stok - "+p.getNama()); final EditText et=new EditText(holder.itemView.getContext()); et.setInputType(InputType.TYPE_CLASS_NUMBER); et.setText(String.valueOf(p.getStok())); b.setView(et); b.setPositiveButton("Simpan", (dialog, which)->{ String s=et.getText().toString().trim(); if(s.isEmpty()){ Toast.makeText(holder.itemView.getContext(),"Isi stok",Toast.LENGTH_SHORT).show(); return; } int newStok=Integer.parseInt(s); db.collection("pagade_produk").document(p.getId()).update("stok",newStok).addOnSuccessListener(a->{ Toast.makeText(holder.itemView.getContext(),"Stok diperbarui",Toast.LENGTH_SHORT).show(); p.setStok(newStok); notifyDataSetChanged(); }).addOnFailureListener(e->Toast.makeText(holder.itemView.getContext(),"Gagal: "+e.getMessage(),Toast.LENGTH_LONG).show()); }); b.setNegativeButton("Batal",null); b.show(); }
  @Override public int getItemCount(){ return list.size(); }
  public static class VH extends RecyclerView.ViewHolder{ TextView tvName,tvPrice,tvStock; Button btnEditStock,btnDelete; public VH(@NonNull View itemView){ super(itemView); tvName=itemView.findViewById(R.id.tvProductName); tvPrice=itemView.findViewById(R.id.tvProductPrice); tvStock=itemView.findViewById(R.id.tvProductStock); btnEditStock=itemView.findViewById(R.id.btnEditStock); btnDelete=itemView.findViewById(R.id.btnDeleteProduct); } }
}
