package com.simpati.bontoharu.simpatika;
import android.app.AlertDialog; import android.os.Bundle; import android.text.InputType; import android.widget.Button; import android.widget.EditText; import android.widget.LinearLayout; import android.widget.Toast;
import androidx.appcompat.app.AppCompatActivity; import androidx.recyclerview.widget.LinearLayoutManager; import androidx.recyclerview.widget.RecyclerView;
import com.google.firebase.firestore.FirebaseFirestore;
import java.util.ArrayList; import java.util.HashMap; import java.util.Map;
public class PagadeActivity extends AppCompatActivity {
  private RecyclerView recyclerView; private Button btnAdd; private FirebaseFirestore db; private PagadeAdapter adapter; private ArrayList<PagadeProduct> list = new ArrayList<>();
  @Override protected void onCreate(Bundle s){ super.onCreate(s); setContentView(R.layout.activity_pagade); db=FirebaseFirestore.getInstance(); recyclerView=findViewById(R.id.recyclerPagade); btnAdd=findViewById(R.id.btnAddProduct); recyclerView.setLayoutManager(new LinearLayoutManager(this)); adapter=new PagadeAdapter(list, db); recyclerView.setAdapter(adapter); loadProducts(); btnAdd.setOnClickListener(v->showAddDialog()); }
  private void loadProducts(){ db.collection("pagade_produk").get().addOnSuccessListener(query->{ list.clear(); for(com.google.firebase.firestore.QueryDocumentSnapshot doc: query){ PagadeProduct p = doc.toObject(PagadeProduct.class); p.setId(doc.getId()); list.add(p);} adapter.notifyDataSetChanged(); }).addOnFailureListener(e-> Toast.makeText(this,"Gagal memuat produk: "+e.getMessage(),Toast.LENGTH_LONG).show()); }
  private void showAddDialog(){ AlertDialog.Builder b = new AlertDialog.Builder(this); b.setTitle("Tambah Produk"); LinearLayout layout = new LinearLayout(this); layout.setOrientation(LinearLayout.VERTICAL); final EditText etName = new EditText(this); etName.setHint("Nama"); layout.addView(etName); final EditText etPrice = new EditText(this); etPrice.setHint("Harga"); etPrice.setInputType(InputType.TYPE_CLASS_NUMBER); layout.addView(etPrice); final EditText etStock = new EditText(this); etStock.setHint("Stok"); etStock.setInputType(InputType.TYPE_CLASS_NUMBER); layout.addView(etStock); b.setView(layout); b.setPositiveButton("Tambah", (dialog, which) -> { String nama = etName.getText().toString().trim(); String harga = etPrice.getText().toString().trim(); String stok = etStock.getText().toString().trim(); if(nama.isEmpty()||harga.isEmpty()||stok.isEmpty()){ Toast.makeText(this, "Isi semua field", Toast.LENGTH_SHORT).show(); return; } Map<String,Object> data = new HashMap<>(); data.put("nama", nama); data.put("harga", Integer.parseInt(harga)); data.put("stok", Integer.parseInt(stok)); db.collection("pagade_produk").add(data).addOnSuccessListener(doc->{ Toast.makeText(this,"Produk ditambahkan",Toast.LENGTH_SHORT).show(); loadProducts(); }).addOnFailureListener(e-> Toast.makeText(this,"Gagal: "+e.getMessage(),Toast.LENGTH_LONG).show()); }); b.setNegativeButton("Batal", null); b.show(); }
}
